package model;
// Generated 10/07/2016 10:54:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Candidato generated by hbm2java
 */
@Entity
@Table(name = "candidato", catalog = "sistemasae"
)
@Inheritance(strategy = InheritanceType.JOINED)
@PrimaryKeyJoinColumn(name = "pessoa_id")
public class Candidato extends Pessoa implements java.io.Serializable {

    private int idCandidato;
    private Bolsistacontemplado bolsistacontemplado;
    private Curso curso;
    private Formulariosocioeconomico formulariosocioeconomico;

    public Candidato() {
    }

    public Candidato(Bolsistacontemplado bolsistacontemplado, Curso curso, Formulariosocioeconomico formulariosocioeconomico) {
        this.bolsistacontemplado = bolsistacontemplado;
        this.curso = curso;
        this.formulariosocioeconomico = formulariosocioeconomico;
    }

    public Candidato(Bolsistacontemplado bolsistacontemplado, Curso curso, Formulariosocioeconomico formulariosocioeconomico, int id, String nome, String nascimento, String logradouro, String cidade, String estado, String matricula, String login, String senha, String confirmasenha) {
        super(id, nome, nascimento, logradouro, cidade, estado, matricula, login, senha, confirmasenha);
        this.idCandidato = id;
        this.bolsistacontemplado = bolsistacontemplado;
        this.curso = curso;
        this.formulariosocioeconomico = formulariosocioeconomico;
    }
    
    @Column(name = "idcandidatos", unique = true, nullable = false)
    public int getIdCandidato() {
        return this.idCandidato;
    }

    public void setIdCandidato(int id) {
        this.idCandidato = id;
    }
    

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bolsistacontemplado_id", nullable = false)
    public Bolsistacontemplado getBolsistacontemplado() {
        return this.bolsistacontemplado;
    }

    public void setBolsistacontemplado(Bolsistacontemplado bolsistacontemplado) {
        this.bolsistacontemplado = bolsistacontemplado;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "curso_idCurso", nullable = false)
    public Curso getCurso() {
        return this.curso;
    }

    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "formulariosocioeconomico_id", nullable = false)
    public Formulariosocioeconomico getFormulariosocioeconomico() {
        return this.formulariosocioeconomico;
    }

    public void setFormulariosocioeconomico(Formulariosocioeconomico formulariosocioeconomico) {
        this.formulariosocioeconomico = formulariosocioeconomico;
    }


}
