package model;
// Generated 10/07/2016 10:54:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "curso", catalog = "sistemasae"
)
public class Curso implements java.io.Serializable {

    private int idCurso;
    private String turno;
    private String curso;
    private int totalPeriodos;

    public Curso() {
    }

    public Curso(int idCurso, String turno, String curso, int totalPeriodos) {
        this.idCurso = idCurso;
        this.turno = turno;
        this.curso = curso;
        this.totalPeriodos = totalPeriodos;
    }

    @Id

    @Column(name = "idCurso", unique = true, nullable = false)
    public int getIdCurso() {
        return this.idCurso;
    }

    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }

    @Column(name = "turno", nullable = false, length = 45)
    public String getTurno() {
        return this.turno;
    }

    public void setTurno(String turno) {
        this.turno = turno;
    }

    @Column(name = "curso", nullable = false, length = 45)
    public String getCurso() {
        return this.curso;
    }

    public void setCurso(String curso) {
        this.curso = curso;
    }

    @Column(name = "totalPeriodos", nullable = false)
    public int getTotalPeriodos() {
        return this.totalPeriodos;
    }

    public void setTotalPeriodos(int totalPeriodos) {
        this.totalPeriodos = totalPeriodos;
    }

}
