package model;
// Generated 10/07/2016 10:54:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Edital generated by hbm2java
 */
@Entity
@Table(name = "edital", catalog = "sistemasae"
)
public class Edital implements java.io.Serializable {

    private int codEdital;
    private int prazo;
    private int data;
    private int numero;
    private String publicacao;
    private String tipoBolsa;

    public Edital() {
    }

    public Edital(int codEdital, int prazo, int data, int numero, String publicacao, String tipoBolsa) {
        this.codEdital = codEdital;
        this.prazo = prazo;
        this.data = data;
        this.numero = numero;
        this.publicacao = publicacao;
        this.tipoBolsa = tipoBolsa;
    }

    @Id

    @Column(name = "codEdital", unique = true, nullable = false)
    public int getCodEdital() {
        return this.codEdital;
    }

    public void setCodEdital(int codEdital) {
        this.codEdital = codEdital;
    }

    @Column(name = "prazo", nullable = false)
    public int getPrazo() {
        return this.prazo;
    }

    public void setPrazo(int prazo) {
        this.prazo = prazo;
    }

    @Column(name = "Data", nullable = false)
    public int getData() {
        return this.data;
    }

    public void setData(int data) {
        this.data = data;
    }

    @Column(name = "numero", nullable = false)
    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    @Column(name = "publicacao", nullable = false)
    public String getPublicacao() {
        return this.publicacao;
    }

    public void setPublicacao(String publicacao) {
        this.publicacao = publicacao;
    }

    @Column(name = "tipoBolsa", nullable = false, length = 45)
    public String getTipoBolsa() {
        return this.tipoBolsa;
    }

    public void setTipoBolsa(String tipoBolsa) {
        this.tipoBolsa = tipoBolsa;
    }

}
