package model;
// Generated 10/07/2016 10:54:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Formulariosocioeconomico generated by hbm2java
 */
@Entity
@Table(name = "formulariosocioeconomico", catalog = "sistemasae", uniqueConstraints = @UniqueConstraint(columnNames = "rg")
)
public class Formulariosocioeconomico implements java.io.Serializable {

    private int id;
    private String nome;
    private int nascimento;
    private String sexo;
    private int rg;
    private int cpf;
    private int telefone;
    private int celular;
    private String email;
    private String rua;
    private String complemento;
    private String bairro;
    private String estado;
    private String cidade;
    private int numero;
    private int cep;
    private String rua1;
    private String complemento1;
    private String bairro1;
    private String estado1;
    private String cidade1;
    private int numero1;
    private int cep1;
    private int telefone1;
    private int celular1;
    private String curso;
    private String ensino;
    private String turno;
    private int periodo;
    private int matricula;
    private int anoT;
    private int anoI;
    private String questao1;
    private String questao2;
    private String questao3;
    private String questao4;
    private String questao5;
    private String questao6;
    private String questao7;
    private String questao8;
    private String questao9;
    private String questao10;
    private String questao11;
    private String questao11a;
    private String questao11b;
    private String questao11c;
    private String questao11d;
    private String questao12;
    private String questao13;
    private String questao14;
    private String questao15;
    private int questao16a;
    private int questao16b;
    private int questao16c;
    private int questao16d;
    private int questao16e;
    private int questao16f;
    private int questao16g;
    private int questao16h;
    private int questao16i;
    private int questao16j;
    private int questao16k;
    private float questao17a;
    private float questao17b;
    private float questao17c;
    private float questao17d;
    private float questao17e;
    private float questao17f;
    private float questao17g;
    private float questao17h;
    private float questao17i;
    private float questao17j;
    private float questao17k;
    private float questao17l;
    private float questao18;
    private float questao18a;
    private float questao18b;
    private float questao18c;
    private float questao18d;
    private float questao18e;
    private String questao19;

    public Formulariosocioeconomico() {
    }

    public Formulariosocioeconomico(int id, String nome, int nascimento, String sexo, int rg, int cpf, int telefone, int celular, String email, String rua, String complemento, String bairro, String estado, String cidade, int numero, int cep, String rua1, String complemento1, String bairro1, String estado1, String cidade1, int numero1, int cep1, int telefone1, int celular1, String curso, String ensino, String turno, int periodo, int matricula, int anoT, int anoI, int questao16a, int questao16b, int questao16c, int questao16d, int questao16e, int questao16f, int questao16g, int questao16h, int questao16i, int questao16j, int questao16k, float questao17a, float questao17b, float questao17c, float questao17d, float questao17e, float questao17f, float questao17g, float questao17h, float questao17i, float questao17j, float questao17k, float questao17l, float questao18, float questao18a, float questao18b, float questao18c, float questao18d, float questao18e, String questao19) {
        this.id = id;
        this.nome = nome;
        this.nascimento = nascimento;
        this.sexo = sexo;
        this.rg = rg;
        this.cpf = cpf;
        this.telefone = telefone;
        this.celular = celular;
        this.email = email;
        this.rua = rua;
        this.complemento = complemento;
        this.bairro = bairro;
        this.estado = estado;
        this.cidade = cidade;
        this.numero = numero;
        this.cep = cep;
        this.rua1 = rua1;
        this.complemento1 = complemento1;
        this.bairro1 = bairro1;
        this.estado1 = estado1;
        this.cidade1 = cidade1;
        this.numero1 = numero1;
        this.cep1 = cep1;
        this.telefone1 = telefone1;
        this.celular1 = celular1;
        this.curso = curso;
        this.ensino = ensino;
        this.turno = turno;
        this.periodo = periodo;
        this.matricula = matricula;
        this.anoT = anoT;
        this.anoI = anoI;
        this.questao16a = questao16a;
        this.questao16b = questao16b;
        this.questao16c = questao16c;
        this.questao16d = questao16d;
        this.questao16e = questao16e;
        this.questao16f = questao16f;
        this.questao16g = questao16g;
        this.questao16h = questao16h;
        this.questao16i = questao16i;
        this.questao16j = questao16j;
        this.questao16k = questao16k;
        this.questao17a = questao17a;
        this.questao17b = questao17b;
        this.questao17c = questao17c;
        this.questao17d = questao17d;
        this.questao17e = questao17e;
        this.questao17f = questao17f;
        this.questao17g = questao17g;
        this.questao17h = questao17h;
        this.questao17i = questao17i;
        this.questao17j = questao17j;
        this.questao17k = questao17k;
        this.questao17l = questao17l;
        this.questao18 = questao18;
        this.questao18a = questao18a;
        this.questao18b = questao18b;
        this.questao18c = questao18c;
        this.questao18d = questao18d;
        this.questao18e = questao18e;
        this.questao19 = questao19;
    }

    public Formulariosocioeconomico(int id, String nome, int nascimento, String sexo, int rg, int cpf, int telefone, int celular, String email, String rua, String complemento, String bairro, String estado, String cidade, int numero, int cep, String rua1, String complemento1, String bairro1, String estado1, String cidade1, int numero1, int cep1, int telefone1, int celular1, String curso, String ensino, String turno, int periodo, int matricula, int anoT, int anoI, String questao1, String questao2, String questao3, String questao4, String questao5, String questao6, String questao7, String questao8, String questao9, String questao10, String questao11, String questao11a, String questao11b, String questao11c, String questao11d, String questao12, String questao13, String questao14, String questao15, int questao16a, int questao16b, int questao16c, int questao16d, int questao16e, int questao16f, int questao16g, int questao16h, int questao16i, int questao16j, int questao16k, float questao17a, float questao17b, float questao17c, float questao17d, float questao17e, float questao17f, float questao17g, float questao17h, float questao17i, float questao17j, float questao17k, float questao17l, float questao18, float questao18a, float questao18b, float questao18c, float questao18d, float questao18e, String questao19) {
        this.id = id;
        this.nome = nome;
        this.nascimento = nascimento;
        this.sexo = sexo;
        this.rg = rg;
        this.cpf = cpf;
        this.telefone = telefone;
        this.celular = celular;
        this.email = email;
        this.rua = rua;
        this.complemento = complemento;
        this.bairro = bairro;
        this.estado = estado;
        this.cidade = cidade;
        this.numero = numero;
        this.cep = cep;
        this.rua1 = rua1;
        this.complemento1 = complemento1;
        this.bairro1 = bairro1;
        this.estado1 = estado1;
        this.cidade1 = cidade1;
        this.numero1 = numero1;
        this.cep1 = cep1;
        this.telefone1 = telefone1;
        this.celular1 = celular1;
        this.curso = curso;
        this.ensino = ensino;
        this.turno = turno;
        this.periodo = periodo;
        this.matricula = matricula;
        this.anoT = anoT;
        this.anoI = anoI;
        this.questao1 = questao1;
        this.questao2 = questao2;
        this.questao3 = questao3;
        this.questao4 = questao4;
        this.questao5 = questao5;
        this.questao6 = questao6;
        this.questao7 = questao7;
        this.questao8 = questao8;
        this.questao9 = questao9;
        this.questao10 = questao10;
        this.questao11 = questao11;
        this.questao11a = questao11a;
        this.questao11b = questao11b;
        this.questao11c = questao11c;
        this.questao11d = questao11d;
        this.questao12 = questao12;
        this.questao13 = questao13;
        this.questao14 = questao14;
        this.questao15 = questao15;
        this.questao16a = questao16a;
        this.questao16b = questao16b;
        this.questao16c = questao16c;
        this.questao16d = questao16d;
        this.questao16e = questao16e;
        this.questao16f = questao16f;
        this.questao16g = questao16g;
        this.questao16h = questao16h;
        this.questao16i = questao16i;
        this.questao16j = questao16j;
        this.questao16k = questao16k;
        this.questao17a = questao17a;
        this.questao17b = questao17b;
        this.questao17c = questao17c;
        this.questao17d = questao17d;
        this.questao17e = questao17e;
        this.questao17f = questao17f;
        this.questao17g = questao17g;
        this.questao17h = questao17h;
        this.questao17i = questao17i;
        this.questao17j = questao17j;
        this.questao17k = questao17k;
        this.questao17l = questao17l;
        this.questao18 = questao18;
        this.questao18a = questao18a;
        this.questao18b = questao18b;
        this.questao18c = questao18c;
        this.questao18d = questao18d;
        this.questao18e = questao18e;
        this.questao19 = questao19;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nome", nullable = false)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "nascimento", nullable = false)
    public int getNascimento() {
        return this.nascimento;
    }

    public void setNascimento(int nascimento) {
        this.nascimento = nascimento;
    }

    @Column(name = "sexo", nullable = false, length = 45)
    public String getSexo() {
        return this.sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    @Column(name = "rg", unique = true, nullable = false)
    public int getRg() {
        return this.rg;
    }

    public void setRg(int rg) {
        this.rg = rg;
    }

    @Column(name = "cpf", nullable = false)
    public int getCpf() {
        return this.cpf;
    }

    public void setCpf(int cpf) {
        this.cpf = cpf;
    }

    @Column(name = "telefone", nullable = false)
    public int getTelefone() {
        return this.telefone;
    }

    public void setTelefone(int telefone) {
        this.telefone = telefone;
    }

    @Column(name = "celular", nullable = false)
    public int getCelular() {
        return this.celular;
    }

    public void setCelular(int celular) {
        this.celular = celular;
    }

    @Column(name = "email", nullable = false)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "rua", nullable = false, length = 200)
    public String getRua() {
        return this.rua;
    }

    public void setRua(String rua) {
        this.rua = rua;
    }

    @Column(name = "complemento", nullable = false, length = 200)
    public String getComplemento() {
        return this.complemento;
    }

    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    @Column(name = "bairro", nullable = false, length = 200)
    public String getBairro() {
        return this.bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    @Column(name = "estado", nullable = false, length = 200)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "cidade", nullable = false, length = 200)
    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    @Column(name = "numero", nullable = false)
    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    @Column(name = "cep", nullable = false)
    public int getCep() {
        return this.cep;
    }

    public void setCep(int cep) {
        this.cep = cep;
    }

    @Column(name = "rua1", nullable = false, length = 200)
    public String getRua1() {
        return this.rua1;
    }

    public void setRua1(String rua1) {
        this.rua1 = rua1;
    }

    @Column(name = "complemento1", nullable = false, length = 200)
    public String getComplemento1() {
        return this.complemento1;
    }

    public void setComplemento1(String complemento1) {
        this.complemento1 = complemento1;
    }

    @Column(name = "bairro1", nullable = false, length = 200)
    public String getBairro1() {
        return this.bairro1;
    }

    public void setBairro1(String bairro1) {
        this.bairro1 = bairro1;
    }

    @Column(name = "estado1", nullable = false, length = 200)
    public String getEstado1() {
        return this.estado1;
    }

    public void setEstado1(String estado1) {
        this.estado1 = estado1;
    }

    @Column(name = "cidade1", nullable = false, length = 200)
    public String getCidade1() {
        return this.cidade1;
    }

    public void setCidade1(String cidade1) {
        this.cidade1 = cidade1;
    }

    @Column(name = "numero1", nullable = false)
    public int getNumero1() {
        return this.numero1;
    }

    public void setNumero1(int numero1) {
        this.numero1 = numero1;
    }

    @Column(name = "cep1", nullable = false)
    public int getCep1() {
        return this.cep1;
    }

    public void setCep1(int cep1) {
        this.cep1 = cep1;
    }

    @Column(name = "telefone1", nullable = false)
    public int getTelefone1() {
        return this.telefone1;
    }

    public void setTelefone1(int telefone1) {
        this.telefone1 = telefone1;
    }

    @Column(name = "celular1", nullable = false)
    public int getCelular1() {
        return this.celular1;
    }

    public void setCelular1(int celular1) {
        this.celular1 = celular1;
    }

    @Column(name = "curso", nullable = false, length = 200)
    public String getCurso() {
        return this.curso;
    }

    public void setCurso(String curso) {
        this.curso = curso;
    }

    @Column(name = "ensino", nullable = false, length = 200)
    public String getEnsino() {
        return this.ensino;
    }

    public void setEnsino(String ensino) {
        this.ensino = ensino;
    }

    @Column(name = "turno", nullable = false, length = 200)
    public String getTurno() {
        return this.turno;
    }

    public void setTurno(String turno) {
        this.turno = turno;
    }

    @Column(name = "periodo", nullable = false)
    public int getPeriodo() {
        return this.periodo;
    }

    public void setPeriodo(int periodo) {
        this.periodo = periodo;
    }

    @Column(name = "matricula", nullable = false)
    public int getMatricula() {
        return this.matricula;
    }

    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }

    @Column(name = "anoT", nullable = false)
    public int getAnoT() {
        return this.anoT;
    }

    public void setAnoT(int anoT) {
        this.anoT = anoT;
    }

    @Column(name = "anoI", nullable = false)
    public int getAnoI() {
        return this.anoI;
    }

    public void setAnoI(int anoI) {
        this.anoI = anoI;
    }

    @Column(name = "questao1", length = 200)
    public String getQuestao1() {
        return this.questao1;
    }

    public void setQuestao1(String questao1) {
        this.questao1 = questao1;
    }

    @Column(name = "questao2", length = 200)
    public String getQuestao2() {
        return this.questao2;
    }

    public void setQuestao2(String questao2) {
        this.questao2 = questao2;
    }

    @Column(name = "questao3", length = 200)
    public String getQuestao3() {
        return this.questao3;
    }

    public void setQuestao3(String questao3) {
        this.questao3 = questao3;
    }

    @Column(name = "questao4", length = 200)
    public String getQuestao4() {
        return this.questao4;
    }

    public void setQuestao4(String questao4) {
        this.questao4 = questao4;
    }

    @Column(name = "questao5", length = 200)
    public String getQuestao5() {
        return this.questao5;
    }

    public void setQuestao5(String questao5) {
        this.questao5 = questao5;
    }

    @Column(name = "questao6", length = 200)
    public String getQuestao6() {
        return this.questao6;
    }

    public void setQuestao6(String questao6) {
        this.questao6 = questao6;
    }

    @Column(name = "questao7", length = 200)
    public String getQuestao7() {
        return this.questao7;
    }

    public void setQuestao7(String questao7) {
        this.questao7 = questao7;
    }

    @Column(name = "questao8", length = 200)
    public String getQuestao8() {
        return this.questao8;
    }

    public void setQuestao8(String questao8) {
        this.questao8 = questao8;
    }

    @Column(name = "questao9", length = 200)
    public String getQuestao9() {
        return this.questao9;
    }

    public void setQuestao9(String questao9) {
        this.questao9 = questao9;
    }

    @Column(name = "questao10", length = 200)
    public String getQuestao10() {
        return this.questao10;
    }

    public void setQuestao10(String questao10) {
        this.questao10 = questao10;
    }

    @Column(name = "questao11", length = 200)
    public String getQuestao11() {
        return this.questao11;
    }

    public void setQuestao11(String questao11) {
        this.questao11 = questao11;
    }

    @Column(name = "questao11a", length = 200)
    public String getQuestao11a() {
        return this.questao11a;
    }

    public void setQuestao11a(String questao11a) {
        this.questao11a = questao11a;
    }

    @Column(name = "questao11b", length = 200)
    public String getQuestao11b() {
        return this.questao11b;
    }

    public void setQuestao11b(String questao11b) {
        this.questao11b = questao11b;
    }

    @Column(name = "questao11c", length = 200)
    public String getQuestao11c() {
        return this.questao11c;
    }

    public void setQuestao11c(String questao11c) {
        this.questao11c = questao11c;
    }

    @Column(name = "questao11d", length = 200)
    public String getQuestao11d() {
        return this.questao11d;
    }

    public void setQuestao11d(String questao11d) {
        this.questao11d = questao11d;
    }

    @Column(name = "questao12", length = 200)
    public String getQuestao12() {
        return this.questao12;
    }

    public void setQuestao12(String questao12) {
        this.questao12 = questao12;
    }

    @Column(name = "questao13", length = 200)
    public String getQuestao13() {
        return this.questao13;
    }

    public void setQuestao13(String questao13) {
        this.questao13 = questao13;
    }

    @Column(name = "questao14", length = 200)
    public String getQuestao14() {
        return this.questao14;
    }

    public void setQuestao14(String questao14) {
        this.questao14 = questao14;
    }

    @Column(name = "questao15", length = 200)
    public String getQuestao15() {
        return this.questao15;
    }

    public void setQuestao15(String questao15) {
        this.questao15 = questao15;
    }

    @Column(name = "questao16a", nullable = false)
    public int getQuestao16a() {
        return this.questao16a;
    }

    public void setQuestao16a(int questao16a) {
        this.questao16a = questao16a;
    }

    @Column(name = "questao16b", nullable = false)
    public int getQuestao16b() {
        return this.questao16b;
    }

    public void setQuestao16b(int questao16b) {
        this.questao16b = questao16b;
    }

    @Column(name = "questao16c", nullable = false)
    public int getQuestao16c() {
        return this.questao16c;
    }

    public void setQuestao16c(int questao16c) {
        this.questao16c = questao16c;
    }

    @Column(name = "questao16d", nullable = false)
    public int getQuestao16d() {
        return this.questao16d;
    }

    public void setQuestao16d(int questao16d) {
        this.questao16d = questao16d;
    }

    @Column(name = "questao16e", nullable = false)
    public int getQuestao16e() {
        return this.questao16e;
    }

    public void setQuestao16e(int questao16e) {
        this.questao16e = questao16e;
    }

    @Column(name = "questao16f", nullable = false)
    public int getQuestao16f() {
        return this.questao16f;
    }

    public void setQuestao16f(int questao16f) {
        this.questao16f = questao16f;
    }

    @Column(name = "questao16g", nullable = false)
    public int getQuestao16g() {
        return this.questao16g;
    }

    public void setQuestao16g(int questao16g) {
        this.questao16g = questao16g;
    }

    @Column(name = "questao16h", nullable = false)
    public int getQuestao16h() {
        return this.questao16h;
    }

    public void setQuestao16h(int questao16h) {
        this.questao16h = questao16h;
    }

    @Column(name = "questao16i", nullable = false)
    public int getQuestao16i() {
        return this.questao16i;
    }

    public void setQuestao16i(int questao16i) {
        this.questao16i = questao16i;
    }

    @Column(name = "questao16j", nullable = false)
    public int getQuestao16j() {
        return this.questao16j;
    }

    public void setQuestao16j(int questao16j) {
        this.questao16j = questao16j;
    }

    @Column(name = "questao16k", nullable = false)
    public int getQuestao16k() {
        return this.questao16k;
    }

    public void setQuestao16k(int questao16k) {
        this.questao16k = questao16k;
    }

    @Column(name = "questao17a", nullable = false, precision = 12, scale = 0)
    public float getQuestao17a() {
        return this.questao17a;
    }

    public void setQuestao17a(float questao17a) {
        this.questao17a = questao17a;
    }

    @Column(name = "questao17b", nullable = false, precision = 12, scale = 0)
    public float getQuestao17b() {
        return this.questao17b;
    }

    public void setQuestao17b(float questao17b) {
        this.questao17b = questao17b;
    }

    @Column(name = "questao17c", nullable = false, precision = 12, scale = 0)
    public float getQuestao17c() {
        return this.questao17c;
    }

    public void setQuestao17c(float questao17c) {
        this.questao17c = questao17c;
    }

    @Column(name = "questao17d", nullable = false, precision = 12, scale = 0)
    public float getQuestao17d() {
        return this.questao17d;
    }

    public void setQuestao17d(float questao17d) {
        this.questao17d = questao17d;
    }

    @Column(name = "questao17e", nullable = false, precision = 12, scale = 0)
    public float getQuestao17e() {
        return this.questao17e;
    }

    public void setQuestao17e(float questao17e) {
        this.questao17e = questao17e;
    }

    @Column(name = "questao17f", nullable = false, precision = 12, scale = 0)
    public float getQuestao17f() {
        return this.questao17f;
    }

    public void setQuestao17f(float questao17f) {
        this.questao17f = questao17f;
    }

    @Column(name = "questao17g", nullable = false, precision = 12, scale = 0)
    public float getQuestao17g() {
        return this.questao17g;
    }

    public void setQuestao17g(float questao17g) {
        this.questao17g = questao17g;
    }

    @Column(name = "questao17h", nullable = false, precision = 12, scale = 0)
    public float getQuestao17h() {
        return this.questao17h;
    }

    public void setQuestao17h(float questao17h) {
        this.questao17h = questao17h;
    }

    @Column(name = "questao17i", nullable = false, precision = 12, scale = 0)
    public float getQuestao17i() {
        return this.questao17i;
    }

    public void setQuestao17i(float questao17i) {
        this.questao17i = questao17i;
    }

    @Column(name = "questao17j", nullable = false, precision = 12, scale = 0)
    public float getQuestao17j() {
        return this.questao17j;
    }

    public void setQuestao17j(float questao17j) {
        this.questao17j = questao17j;
    }

    @Column(name = "questao17k", nullable = false, precision = 12, scale = 0)
    public float getQuestao17k() {
        return this.questao17k;
    }

    public void setQuestao17k(float questao17k) {
        this.questao17k = questao17k;
    }

    @Column(name = "questao17l", nullable = false, precision = 12, scale = 0)
    public float getQuestao17l() {
        return this.questao17l;
    }

    public void setQuestao17l(float questao17l) {
        this.questao17l = questao17l;
    }

    @Column(name = "questao18", nullable = false, precision = 12, scale = 0)
    public float getQuestao18() {
        return this.questao18;
    }

    public void setQuestao18(float questao18) {
        this.questao18 = questao18;
    }

    @Column(name = "questao18a", nullable = false, precision = 12, scale = 0)
    public float getQuestao18a() {
        return this.questao18a;
    }

    public void setQuestao18a(float questao18a) {
        this.questao18a = questao18a;
    }

    @Column(name = "questao18b", nullable = false, precision = 12, scale = 0)
    public float getQuestao18b() {
        return this.questao18b;
    }

    public void setQuestao18b(float questao18b) {
        this.questao18b = questao18b;
    }

    @Column(name = "questao18c", nullable = false, precision = 12, scale = 0)
    public float getQuestao18c() {
        return this.questao18c;
    }

    public void setQuestao18c(float questao18c) {
        this.questao18c = questao18c;
    }

    @Column(name = "questao18d", nullable = false, precision = 12, scale = 0)
    public float getQuestao18d() {
        return this.questao18d;
    }

    public void setQuestao18d(float questao18d) {
        this.questao18d = questao18d;
    }

    @Column(name = "questao18e", nullable = false, precision = 12, scale = 0)
    public float getQuestao18e() {
        return this.questao18e;
    }

    public void setQuestao18e(float questao18e) {
        this.questao18e = questao18e;
    }

    @Column(name = "questao19", nullable = false, length = 200)
    public String getQuestao19() {
        return this.questao19;
    }

    public void setQuestao19(String questao19) {
        this.questao19 = questao19;
    }

}
