package model;
// Generated 10/07/2016 10:54:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Funcionario generated by hbm2java
 */
@Entity
@Table(name = "funcionario", catalog = "sistemasae"
)
@Inheritance(strategy = InheritanceType.JOINED)
@PrimaryKeyJoinColumn(name = "pessoa_id")
public class Funcionario extends Pessoa implements java.io.Serializable {

    private int idFuncionario;
    private String setor;
    private String gerente;

    public Funcionario() {
    }

    public Funcionario(String setor, String gerente) {
        this.setor = setor;
        this.gerente = gerente;
    }

    public Funcionario(String setor, String gerente, int id, String nome, String nascimento, String logradouro, String cidade, String estado, String matricula, String login, String senha, String confirmasenha) {
        super(id, nome, nascimento, logradouro, cidade, estado, matricula, login, senha, confirmasenha);
        this.setor = setor;
        this.gerente = gerente;
    }

    @Column(name = "idFuncionario", unique = true, nullable = false)
    public Integer getIdFuncionario() {
        return this.idFuncionario;
    }

    public void setIdFuncionario(Integer idFuncionario) {
        this.idFuncionario = idFuncionario;
    }

    @Column(name = "setor", length = 45)
    public String getSetor() {
        return this.setor;
    }

    public void setSetor(String setor) {
        this.setor = setor;
    }

    @Column(name = "gerente", length = 50)
    public String getGerente() {
        return this.gerente;
    }

    public void setGerente(String gerente) {
        this.gerente = gerente;
    }

}
