package model;
// Generated 10/07/2016 10:54:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name = "pessoa", catalog = "sistemasae", uniqueConstraints = @UniqueConstraint(columnNames = "nascimento")
)
@Inheritance(strategy = InheritanceType.JOINED)
public class Pessoa implements java.io.Serializable {

    private int id;
    private String nome;
    private String nascimento;
    private String logradouro;
    private String cidade;
    private String estado;
    private String matricula;
    private String login;
    private String senha;
    private String confirmasenha;

    public Pessoa() {
    }

    public Pessoa(int id) {
        this.id = id;
    }

    public Pessoa(int id, String nome, String nascimento, String logradouro, String cidade, String estado, String matricula, String login, String senha, String confirmasenha) {
        this.id = id;
        this.nome = nome;
        this.nascimento = nascimento;
        this.logradouro = logradouro;
        this.cidade = cidade;
        this.estado = estado;
        this.matricula = matricula;
        this.login = login;
        this.senha = senha;
        this.confirmasenha = confirmasenha;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nome", length = 45)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "nascimento", unique = true, length = 45)
    public String getNascimento() {
        return this.nascimento;
    }

    public void setNascimento(String nascimento) {
        this.nascimento = nascimento;
    }

    @Column(name = "logradouro", length = 45)
    public String getLogradouro() {
        return this.logradouro;
    }

    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    @Column(name = "cidade", length = 45)
    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    @Column(name = "estado", length = 45)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "matricula", length = 45)
    public String getMatricula() {
        return this.matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    @Column(name = "login", length = 45)
    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @Column(name = "senha", length = 45)
    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    @Column(name = "confirmasenha", length = 45)
    public String getConfirmasenha() {
        return this.confirmasenha;
    }

    public void setConfirmasenha(String confirmasenha) {
        this.confirmasenha = confirmasenha;
    }
}
